### ISSUE TITLE
Статистика по транкам

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#101]
Добавить новую страницу в админку — статистика по транкам.  Предложи как лучше её добавить. 

При заходе на страничку админка делает запрос на АПИ:
`GET /accounts/{accountID}/trunks/stats`

В ответ получает статус и данные со статистикой:
```
{
    "status": 200,
    "stats": [{
        "name": "Название транка",
        "customers": количество_клиентов
    }]
}
```
нужно вывести содержимое массива _stats_ в таблицу с двумя колонками: название транка (name) и количество лидов (customers).

**Comment by exoriri** [comment]
1)Можно ее в отдельном табе на странице транков сделать
2)Можно в сайдбар добавить(Но вариант не очень нравится)
3)Можно ссылку на страницу в шапку добавить

**Comment by catindev** [comment]
Давай табом в страницу транков
