### ISSUE TITLE
АПИ для создания аккаунта

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#18]
Для создания нового аккаунта нужно сделать запрос:
`POST /accounts?user_session={значение}`
и передать в body параметр name — название нового аккаунта.

В ответ АПИ возвращает идентификатор нового аккаунта: 
```
{
   status: 200,
   id: "идентификатор"
}
```

Если сессия будет устаревшей, то АПИ вернёт ошибку:
`{ status:403, message: "Ошибка аутентификации" }`

Если не заполнить параметр name, то АПИ вернёт ошибку:
`{ status:400, message: "Название аккаунта не заполнено" }`

**Comment by exoriri** [comment]
> Если не заполнить параметр name, то АПИ вернёт ошибку:
{ status:400, message: "Название аккаунта не заполнено" }

Может ошибку связанную с аккаунтом не надо? Потому что пользователь не сможет отправить форму если она пустая. Там кнопка disabled стоит.

**Comment by catindev** [comment]
Ошибку тебе обрабатывать не надо, но она нужна. Не только ты потом будешь пользоваться этим АПИ
