### ISSUE TITLE
АПИ для редактирования аккаунта

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#20]
Для редактирования аккаунта нужно сделать запрос:
`PUT /accounts/{accountID}?user_session={значение}`
где _accountID_ это идентификатор аккаунта и передать в body параметры.

В ответ АПИ возвращает успешный статус сохранения новых данных: 
```
{
   status: 200
}
```

Если сессия будет устаревшей, то АПИ вернёт ошибку:
`{ status:403, message: "Ошибка аутентификации" }`

Если какой-то из параметров неправильный, то АПИ вернёт ошибку:
```
{ 
  status:400, 
  message: "Неправильно заполнен один из параметров",
  fields: [ "maxWaitingTime" ]
}
```

**Comment by exoriri** [comment]
> Если какой-то из параметров неправильный, то АПИ вернёт ошибку:
{ 
  status:400, 
  message: "Неправильно заполнен один из параметров",
  fields: [ "maxWaitingTime" ]
}

Надо определить на сервере поля,которые неправильно заполнены и добавить их в fields.  А на клиенте выделить эти поля красным цветом. Правильно понимаю?

**Comment by catindev** [comment]
> Надо определить на сервере поля,которые неправильно заполнены

Этого тебе делать не нужно.

> на клиенте выделить эти поля красным цветом

Это нужно, да
