### ISSUE TITLE
Страница транков

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#32]
Страница транков выглядит примерно вот так https://cloudup.com/c3KqQcZwwda

Несколько сценариев:
- При открытии страница сразу запрашивает список транков и выводит их в виде форм у которых сразу есть возможность отредактировать транк или удалить. 
- На странице,  вверху есть форма для создания нового транка. После создания нового транка он должен добавиться в список существующих транков, а под формой нового транка нужно вывести сообщение об добавлении или ошибке.
- При сохранении транка под ним так же должно выводиться сообщение, что транк сохранён.
- Если пользователь удаляет транк, то над таблицей нужно вывести сообщение, что транк был удалён.

Если что-то непонятно, то задай вопросы и уточни. Если увидел какие-то другие сценарии, которые я тут не описал, то расскажи.

**Comment by exoriri** [comment]
>  https://cloudup.com/c3KqQcZwwda

Картинку не грузит

**Comment by exoriri** [comment]
а ссылку для перехода на страницу транков сделать в сайдбаре,да?

**Comment by catindev** [comment]
да, в сайдбаре. добавь ссылку в конфиг в sidebar.js. я добавил в сервер чтобы по ссылке /accounts/{id}/trunks открывалась страница trunks.html
