### ISSUE TITLE
Сброс пароля

### ISSUE THREAD

**Issue by exoriri** [catindev/ms-admin#49]
1)Табы и кнопку для сброса пароля переместить из account переместить в user.

- Запрос для сброса также удалить из аккаунта и вставить в user

**Comment by exoriri** [comment]
1)Табы и кнопку для сброса пароля переместить из account переместить в user.
2)Списки accounts,users,customfields,trunks сделать таблицей (из бутстрапа).
- В заголовке таблицы должны быть: № и Название(аккаунта,транка,параметера)/Имя пользователя

- В ячейках: нумерация и сам список

**Comment by catindev** [comment]
Сделай несколько ишью. 1 задача = 1 ишью + отдельная ветка и реквест
