### ISSUE TITLE
Маржины поменять на паддинги

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#60]
Убрать верхние маржины везде, где задаётся отступ сверху. Вместо этого контейнеру-родителю поставить аналогичный паддинг.

Перед правками сначала составить список мест, где это нужно поправить и написать этот список в комментарий к этой задаче

**Comment by exoriri** [comment]
- Форма аккаунта
- Форма пользователя
- Форма параметра
- Форма для добавления параметра
- Форма для добавления позвователя

**Comment by catindev** [comment]
Получается только формы?

**Comment by exoriri** [comment]
ну,там еще есть кнопки,просто они же как самостоятельные блоки
