### ISSUE TITLE
Добавить поле в форму параметра

### ISSUE THREAD

**Issue by catindev** [catindev/ms-admin#63]
Забыли название
![image](https://user-images.githubusercontent.com/2453616/31497279-71a6e4f8-af80-11e7-8459-85c5fe873933.png)

**Comment by exoriri** [comment]
имя же есть
![screenshot 2017-10-13 09-32-00](https://user-images.githubusercontent.com/29581006/31529162-66e0496e-aff9-11e7-952f-8fb66f70da61.jpg)

**Comment by catindev** [comment]
В форме нет
