### ISSUE TITLE
Баг с сохранением транков

### ISSUE THREAD

**Issue by exoriri** [catindev/ms-admin#67]
1) Убрать перезапись innerHtml при добавлении транка
2)Убрать перезапись innerHtlm при сохранении транка. (добавление сообщения "сохранено")

**Comment by catindev** [comment]
Подожди закрывать. Баг с данными старыми. Причину нашёл?

**Comment by exoriri** [comment]
да,это из-за innerHTML,постоянно перзаписывался. Я переделал теперь нормально работает
