### ISSUE TITLE
Проверка сессии

### ISSUE THREAD

**Issue by exoriri** [catindev/ms-admin#69]
1. Переименовать checksession.js в adminName.js
2. В adminName.js убрать все условия,оставить только запрос на получение имени
2.  со всех файлах переименовать скрипт checksession в adminName
3. Создать новый файл в корневой директории checksession.js
4. Внутри checkSession содать функцию,у которой будет два аргумента request,response
    В теле функции будет браться сессия requets.cookie
    Далее будет условие: если userSession === undefined,тогда res.replace('/')
5. Импортировать checksession в server.js и вызывать созданную функцию во всех запросах,где требуется проверка

**Comment by catindev** [comment]
Какой прогресс по этой задаче?

**Comment by exoriri** [comment]
написал фунцию для проверки,посмотрел что функцию,надо запускать перед middleware,чтобы один раз ее использовать. Только вот плохо понятно,что функция next делает

**Comment by exoriri** [comment]
А еще хотел спросить: как страница входа подключается? Убираю роут,который за нее отвечает она все ровно грузится

**Comment by exoriri** [comment]
вот еще не понятно как отправляется страница входа при запросе? Даже если роут для нее убираешь она работает

**Comment by exoriri** [comment]
Все понял express.static по умолчанию ищет index.html,да?
